body:
  - type: markdown
    attributes:
      value: |
        **Retrospective** 카테고리 블로그 게시글입니다.
  - type: textarea
    id: post-body
    attributes:
      label: 게시글 본문
      value: |
        ---
        slug:
        excerpt:
        coverImage:
        featured: false
        featuredOrder: 1
        published: true
        tags:
          - Retrospective
        ---

        ## 제목

        ## 잘한 점

        -

        ## 아쉬운 점

        -

        ## 다음 액션

        -
    validations:
      required: true
